[tox]
skipsdist = True
envlist = lint, py313

[testenv:lint]
deps = uv
skip_install = true
setenv =
    PYTHONPATH = {toxinidir}
commands =
    uv run ruff check .
    uv run ruff format --check .
    uv run mypy pdf_signoff

[testenv]
deps = uv
skip_install = true
setenv =
    PYTHONPATH = {toxinidir}
commands_pre = uv sync --group dev
commands =
    uv run pytest --cov=pdf_signoff tests/

